query GetProductLinkAndImage($identifier: ProductUniqueIdentifier) {
  product(identifier: $identifier) @context(provider: "vtex.search-graphql") {
    linkText
    productName
    items {
      images {
        imageUrl
      }
    }
  }
}
