query productViewed($identifier: ProductUniqueIdentifier) {
  product(identifier: $identifier) @context(provider: "vtex.search-graphql") {
    productId
    linkText
    productName
    specificationGroups {
      name
      originalName
      specifications {
        name
        originalName
        values
      }
    }
    items {
      sellers {
        sellerId
        commertialOffer {
           Installments(criteria: MAX, rates: true) {
            NumberOfInstallments
            Value
            InterestRate
            TotalValuePlusInterestRate
            PaymentSystemGroupName
            PaymentSystemName
          }
          AvailableQuantity
          Price
          ListPrice
          spotPrice
        }
      }
      images {
        imageLabel
        imageUrl
      }
      variations {
        name
        values
      }
    }
  }
}
